// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Silapa.Models;

#nullable disable

namespace silapa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251017064137_AddSetupAndTimelineTables")]
    partial class AddSetupAndTimelineTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Silapa.Models.Affiliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Affiliation");
                });

            modelBuilder.Entity("Silapa.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("m_id")
                        .HasColumnType("longtext");

                    b.Property<int?>("s_id")
                        .HasColumnType("int");

                    b.Property<string>("titlename")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Silapa.Models.Certificate", b =>
                {
                    b.Property<int>("CertificateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CertificateID"));

                    b.Property<string>("AwardID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AwardName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RegistrationID")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationNo")
                        .HasColumnType("int");

                    b.Property<int>("SettingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CertificateID");

                    b.ToTable("Certificate");
                });

            modelBuilder.Entity("Silapa.Models.Competitionlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("c_id")
                        .HasColumnType("int");

                    b.Property<string>("details")
                        .HasColumnType("longtext");

                    b.Property<int>("director")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<int>("student")
                        .HasColumnType("int");

                    b.Property<int>("teacher")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("c_id");

                    b.ToTable("Competitionlist");
                });

            modelBuilder.Entity("Silapa.Models.NewsImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsImages");
                });

            modelBuilder.Entity("Silapa.Models.Racelocation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Racelocation");
                });

            modelBuilder.Entity("Silapa.Models.Registerdetail", b =>
                {
                    b.Property<int>("no")
                        .HasColumnType("int");

                    b.Property<int>("h_id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("c_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("u_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("no", "h_id", "Type");

                    b.HasIndex("h_id");

                    b.ToTable("Registerdetail");
                });

            modelBuilder.Entity("Silapa.Models.Registerhead", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("SettingID")
                        .HasColumnType("int");

                    b.Property<string>("award")
                        .HasColumnType("longtext");

                    b.Property<int>("c_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("rank")
                        .HasColumnType("int");

                    b.Property<int>("s_id")
                        .HasColumnType("int");

                    b.Property<decimal>("score")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("u_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("SettingID");

                    b.HasIndex("c_id");

                    b.HasIndex("s_id");

                    b.ToTable("Registerhead");
                });

            modelBuilder.Entity("Silapa.Models.TimelineItem", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EventID"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IconNumber")
                        .HasColumnType("int");

                    b.Property<int>("SetupSystemID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("EventID");

                    b.HasIndex("SetupSystemID");

                    b.ToTable("TimelineItem");
                });

            modelBuilder.Entity("Silapa.Models.VisitorCounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("VisitCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VisitorCounts");
                });

            modelBuilder.Entity("Silapa.Models.category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("fullname")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("Silapa.Models.contacts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("u_id")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("Silapa.Models.criterion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("file")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("g_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("criterion");
                });

            modelBuilder.Entity("Silapa.Models.dCompetitionlist", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("h_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<int?>("scrol")
                        .HasColumnType("int");

                    b.Property<string>("u_id")
                        .HasColumnType("longtext");

                    b.HasKey("id", "h_id");

                    b.HasIndex("h_id");

                    b.ToTable("dCompetitionlist");
                });

            modelBuilder.Entity("Silapa.Models.deleteregister", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("c_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("u_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("deleteregister");
                });

            modelBuilder.Entity("Silapa.Models.filelist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("fileurl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<string>("u_id")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("filelist");
                });

            modelBuilder.Entity("Silapa.Models.grouplist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("grouplist");
                });

            modelBuilder.Entity("Silapa.Models.groupreferee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("SettingID")
                        .HasColumnType("int");

                    b.Property<int>("c_id")
                        .HasColumnType("int");

                    b.Property<string>("duty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("total")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("c_id");

                    b.ToTable("groupreferee");
                });

            modelBuilder.Entity("Silapa.Models.news", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BackgroundGradient")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BadgeClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("m_id")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<string>("titlename")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("u_id")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("news");
                });

            modelBuilder.Entity("Silapa.Models.racedetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("SettingID")
                        .HasColumnType("int");

                    b.Property<string>("building")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("c_id")
                        .HasColumnType("int");

                    b.Property<string>("daterace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("r_id")
                        .HasColumnType("int");

                    b.Property<string>("room")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("u_id")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("c_id");

                    b.HasIndex("r_id");

                    b.ToTable("racedetails");
                });

            modelBuilder.Entity("Silapa.Models.referee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("SettingID")
                        .HasColumnType("int");

                    b.Property<int?>("c_id")
                        .HasColumnType("int");

                    b.Property<int?>("g_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("m_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<string>("u_id")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("SettingID");

                    b.HasIndex("c_id");

                    b.HasIndex("g_id");

                    b.ToTable("referee");
                });

            modelBuilder.Entity("Silapa.Models.registerdirector", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("c_id")
                        .HasColumnType("int");

                    b.Property<string>("experience")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("g_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<string>("tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("c_id");

                    b.ToTable("registerdirector");
                });

            modelBuilder.Entity("Silapa.Models.school", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("a_id")
                        .HasColumnType("int");

                    b.Property<int>("g_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<string>("tel")
                        .HasColumnType("longtext");

                    b.Property<string>("titlename")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("a_id");

                    b.HasIndex("g_id");

                    b.ToTable("school");
                });

            modelBuilder.Entity("Silapa.Models.setupsystem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Coordinator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LogoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("carddirector")
                        .HasColumnType("longtext");

                    b.Property<string>("cardreferee")
                        .HasColumnType("longtext");

                    b.Property<string>("cardstudents")
                        .HasColumnType("longtext");

                    b.Property<string>("cardteacher")
                        .HasColumnType("longtext");

                    b.Property<string>("certificate")
                        .HasColumnType("longtext");

                    b.Property<string>("certificatedate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("endedit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("endgisterdate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nameagency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("racedate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("startedit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("startregisterdate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("token")
                        .HasColumnType("longtext");

                    b.Property<string>("u_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("yaer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("setupsystem");
                });

            modelBuilder.Entity("Silapa.Models.uploadfilepdf", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("c_id")
                        .HasColumnType("int");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("lastupdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("msg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("s_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("uploadfilepdf");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Silapa.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Silapa.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Silapa.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Silapa.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Silapa.Models.Competitionlist", b =>
                {
                    b.HasOne("Silapa.Models.category", "Category")
                        .WithMany("competitionlists")
                        .HasForeignKey("c_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Silapa.Models.NewsImage", b =>
                {
                    b.HasOne("Silapa.Models.news", "News")
                        .WithMany("GalleryImages")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("Silapa.Models.Registerdetail", b =>
                {
                    b.HasOne("Silapa.Models.Registerhead", "Registerhead")
                        .WithMany("Registerdetail")
                        .HasForeignKey("h_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registerhead");
                });

            modelBuilder.Entity("Silapa.Models.Registerhead", b =>
                {
                    b.HasOne("Silapa.Models.setupsystem", "Setupsystem")
                        .WithMany()
                        .HasForeignKey("SettingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Silapa.Models.Competitionlist", "Competitionlist")
                        .WithMany("registerheads")
                        .HasForeignKey("c_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Silapa.Models.school", "School")
                        .WithMany("registerheads")
                        .HasForeignKey("s_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competitionlist");

                    b.Navigation("School");

                    b.Navigation("Setupsystem");
                });

            modelBuilder.Entity("Silapa.Models.TimelineItem", b =>
                {
                    b.HasOne("Silapa.Models.setupsystem", "SetupSystem")
                        .WithMany()
                        .HasForeignKey("SetupSystemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SetupSystem");
                });

            modelBuilder.Entity("Silapa.Models.dCompetitionlist", b =>
                {
                    b.HasOne("Silapa.Models.Competitionlist", "Competitionlist")
                        .WithMany("dCompetitionlists")
                        .HasForeignKey("h_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competitionlist");
                });

            modelBuilder.Entity("Silapa.Models.groupreferee", b =>
                {
                    b.HasOne("Silapa.Models.category", "Category")
                        .WithMany("groupreferee")
                        .HasForeignKey("c_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Silapa.Models.racedetails", b =>
                {
                    b.HasOne("Silapa.Models.Competitionlist", "Competitionlist")
                        .WithMany("racedetails")
                        .HasForeignKey("c_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Silapa.Models.Racelocation", "Racelocation")
                        .WithMany("racedetails")
                        .HasForeignKey("r_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competitionlist");

                    b.Navigation("Racelocation");
                });

            modelBuilder.Entity("Silapa.Models.referee", b =>
                {
                    b.HasOne("Silapa.Models.setupsystem", "Setupsystem")
                        .WithMany()
                        .HasForeignKey("SettingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Silapa.Models.Competitionlist", "Competitionlist")
                        .WithMany("referees")
                        .HasForeignKey("c_id");

                    b.HasOne("Silapa.Models.groupreferee", "Groupreferee")
                        .WithMany("referees")
                        .HasForeignKey("g_id");

                    b.Navigation("Competitionlist");

                    b.Navigation("Groupreferee");

                    b.Navigation("Setupsystem");
                });

            modelBuilder.Entity("Silapa.Models.registerdirector", b =>
                {
                    b.HasOne("Silapa.Models.Competitionlist", "Competitionlist")
                        .WithMany("registerdirectors")
                        .HasForeignKey("c_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competitionlist");
                });

            modelBuilder.Entity("Silapa.Models.school", b =>
                {
                    b.HasOne("Silapa.Models.Affiliation", "Affiliation")
                        .WithMany("schools")
                        .HasForeignKey("a_id");

                    b.HasOne("Silapa.Models.grouplist", "grouplist")
                        .WithMany("school")
                        .HasForeignKey("g_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affiliation");

                    b.Navigation("grouplist");
                });

            modelBuilder.Entity("Silapa.Models.Affiliation", b =>
                {
                    b.Navigation("schools");
                });

            modelBuilder.Entity("Silapa.Models.Competitionlist", b =>
                {
                    b.Navigation("dCompetitionlists");

                    b.Navigation("racedetails");

                    b.Navigation("referees");

                    b.Navigation("registerdirectors");

                    b.Navigation("registerheads");
                });

            modelBuilder.Entity("Silapa.Models.Racelocation", b =>
                {
                    b.Navigation("racedetails");
                });

            modelBuilder.Entity("Silapa.Models.Registerhead", b =>
                {
                    b.Navigation("Registerdetail");
                });

            modelBuilder.Entity("Silapa.Models.category", b =>
                {
                    b.Navigation("competitionlists");

                    b.Navigation("groupreferee");
                });

            modelBuilder.Entity("Silapa.Models.grouplist", b =>
                {
                    b.Navigation("school");
                });

            modelBuilder.Entity("Silapa.Models.groupreferee", b =>
                {
                    b.Navigation("referees");
                });

            modelBuilder.Entity("Silapa.Models.news", b =>
                {
                    b.Navigation("GalleryImages");
                });

            modelBuilder.Entity("Silapa.Models.school", b =>
                {
                    b.Navigation("registerheads");
                });
#pragma warning restore 612, 618
        }
    }
}
